title: "Laurin L. Curschellas"
email: lcurschellas@ucdavis.edu
github_username: LaurinCurschellas
logo: /assets/images/profile.jpeg
cv_url: /assets/files/CV_Curschellas_Laurin_03_2026.pdf
baseurl: ""
url: "https://laurincurschellas.github.io"

# SEO Settings
name: "Laurin L. Curschellas"
description: "PhD student in Economics at UC Davis. Research interests in applied econometrics, environmental economics, and policy evaluation."
author:
  name: "Laurin L. Curschellas"
  email: "lcurschellas@ucdavis.edu"

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude common unneeded files
exclude:
  - .DS_Store
  - Gemfile
  - Gemfile.lock
