title: "Laurin L. Curschellas"
email: lcurschellas@ucdavis.edu
description: |
  I'm a 2nd year PhD student in Economics at the University of California, Davis.
  My research interests are applied econometrics and environmental economics.
baseurl: ""
url: "https://laurincurschellas.github.io"
github_username: LaurinCurschellas

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude common unneeded files
exclude:
  - .DS_Store
  - Gemfile
  - Gemfile.lock
